### ISSUE TITLE
Error registering to prod

### ISSUE THREAD

**Issue by milan0v** [lunarway/openbanking#66]
Hi @Crevil, I am tagging you as we had the same problem again before, this time the certificate is for another environment. The all.pem includes the full cert chain. This is what I get:

![image](https://github.com/lunarway/openbanking/assets/75023012/10b26946-b529-4218-bc21-3dbf548abbd5)

Thanks in advance,
Dimitar

**Comment by Crevil** [comment]
Hi Dimitar,

The response indicates a wrong payload of sorts. If you inspect the response body you will see additional details.
I am not familiar enough with the `wget` tool you are using, so please refer to upstream documentation to find this information.

Inspecting the provided payload in this issue, it looks as if you are exceeding the `name` field length limit of 16 characters.
Referring to the [Open API specification documented on the portal](https://developer.openbanking.prod.lunar.app/catalog/default/api/Registration) the limitations of `name` are:

```yaml
      name:
        type: string
        description: Unique name for the client that is being registered.
        pattern: '^[a-z0-9-_.]+$'
        minLength: 1
        maxLength: 16
```

When ever you receive either 400 or 422 it indicates issues with the provided payload and the body of the response will contain additional details helping you figure out _what_ the problem is. In your case I expect your response body to be:

```json
{"code":603,"message":"name in body should be at most 16 chars long"}
```

As reducing the `name` field length should resolve your issue, I will close the issue with above information. If you for some reason are still not able to register, please provide any additional information for us to debug.
